"use client";

import React, { useEffect, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowLeft } from "lucide-react";

export default function DisclaimersPage() {
  const [currentYear, setCurrentYear] = useState<number | string>("");

  useEffect(() => {
    setCurrentYear(new Date().getFullYear());
  }, []);

  return (
    <div className="bg-gray-50 dark:bg-gray-950 min-h-screen py-12 px-4 sm:px-6 lg:px-8 transition-colors duration-200">
      <div className="max-w-3xl mx-auto bg-white dark:bg-gray-900 rounded-2xl border border-gray-200/60 dark:border-gray-800/60 p-6 sm:p-10 shadow-sm">

        {/* Back Link */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 transition-colors mb-8"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>

        {/* Header */}
        <div className="flex items-center gap-3 border-b border-gray-100 dark:border-gray-850 pb-6 mb-8">
          <div className="p-3 rounded-xl bg-amber-50 dark:bg-amber-900/20 text-amber-600 dark:text-amber-400">
            <AlertTriangle className="w-6 h-6" />
          </div>
          <div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-gray-900 dark:text-white">
              Disclaimers & Legal Notice
            </h1>
            <p className="text-xs text-gray-400 dark:text-gray-500 mt-1">
              Consolidated Disclaimers • {currentYear || "..."}
            </p>
          </div>
        </div>

        {/* Content */}
        <div className="space-y-6 text-sm sm:text-base text-gray-600 dark:text-gray-300 leading-relaxed font-sans">
          <p>
            To ensure absolute transparency and your protection, this page consolidates the legal and operational disclaimers that apply to the tools across the Freelance Ops Toolkit. By using any tool on this site, you acknowledge and agree to these terms.
          </p>

          <h2 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white mt-8">
            1. Legal Document Templates
          </h2>
          <p className="text-xs text-gray-400 dark:text-gray-500 italic">
            Applicable to: Contract Template Builder, NDA Generator, Retainer Agreement Generator, Proposal Generator
          </p>
          <blockquote className="border-l-4 border-amber-500 bg-amber-500/5 p-4 rounded-r-xl text-gray-700 dark:text-gray-300 my-4 text-xs sm:text-sm">
            <strong>DISCLAIMER:</strong> The documents generated by these tools are generic templates for informational purposes only and do not constitute legal advice. No attorney-client relationship is established. Laws vary by jurisdiction, state, and country. You must review and customize these templates carefully, and we strongly advise consulting a qualified attorney in your local jurisdiction before using, signing, or presenting these agreements to clients.
          </blockquote>

          <h2 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white mt-8">
            2. Financial & Rate Tools
          </h2>
          <p className="text-xs text-gray-400 dark:text-gray-500 italic">
            Applicable to: Freelance Rate Benchmark Tool, Rate Calculator, Late Payment Fee Calculator, Currency Converter
          </p>
          <blockquote className="border-l-4 border-amber-500 bg-amber-500/5 p-4 rounded-r-xl text-gray-700 dark:text-gray-300 my-4 text-xs sm:text-sm">
            <strong>DISCLAIMER:</strong> All rates, benchmark comparison ranges, currency exchanges, and interest calculations are estimates and simulations intended for reference and planning purposes only. They do not constitute certified financial, tax, or legal planning advice. Market conditions fluctuate, and local rates vary widely based on individual expertise, specific project scopes, and niche demands. Consult a certified public accountant (CPA) or financial advisor regarding your business tax and rate-setting practices.
          </blockquote>

          <h2 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white mt-8">
            3. User Responsibility
          </h2>
          <p>
            You retain full operational and legal responsibility for any documents or numbers generated through this toolkit. Freelance Ops Toolkit does not log or audit your generated assets, meaning the burden of verification and accuracy lies entirely with you, the user.
          </p>
        </div>

      </div>
    </div>
  );
}
